# Site
name: "mrkyia's garage"
#title: "mrkyia's garage, a place where things that were exciting or wanted to remember are piled up."
description: "설레는 것만 남겨두기"
logo: 'assets/images/favicon/android-icon-192x192.png'
favicon: 'assets/images/favicon/favicon.ico'
url: https://mrkyia.github.io
baseurl: 
google_analytics: 'G-ZM5GQWTL0K'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mrkyia:
    name: mrkyia
    display_name: mrkyia
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: gm_mrkyia@gmail.com
    web: https://mrkyia.github.io
    description: "방장"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [Gemfile, Gemfile.lock]
